export const LOCALITIES_CONTENT = {
  en: {
    title: 'CHANDER VIHAR LOCALITIES & COLONIES',
    subtitle: 'Prominent residential colonies and sub-areas in Chander Vihar & Nilothi',
    items: [
      'Abchal Nagar',
      'Dalip Vihar',
      'Davinder Colony',
      'Guru Nanak Encl.',
      'Meera Kunj',
      'Pradhan Market',
      'Teacher Vihar',
      'Udhay Vihar',
      'Himgiri Enclave',
      'Ranjit Vihar',
      'Guru Nanak Vihar',
      'Vikar Puri Extension',
      'Bharat Vihar',
      'Shiv Vihar',
      'Shri Ram Colony',
      'Mahavir Enclave',
      'Arya Nagar',
      'Deepak Vihar',
      'Hukum Vihar',
      'New Har Kishan Nagar',
    ],
  },
  hi: {
    title: 'चंदर विहार के प्रमुख क्षेत्र और कॉलोनियां',
    subtitle: 'चंदर विहार और निलोठी के आसपास की मुख्य रिहायशी कॉलोनियां',
    items: [
      'अबचल नगर',
      'दलीप विहार',
      'दविंदर कॉलोनी',
      'गुरु नानक एनक्लेव',
      'मीरा कुंज',
      'प्रधान मार्केट',
      'टीचर विहार',
      'उदय विहार',
      'हिमगिरी एनक्लेव',
      'रणजीत विहार',
      'गुरु नानक विहार',
      'विकासपुरी एक्सटेंशन',
      'भारत विहार',
      'शिव विहार',
      'श्री राम कॉलोनी',
      'महावीर एनक्लेव',
      'आर्या नगर',
      'दीपक विहार',
      'हुकूम विहार',
      'न्यू हरकिशन नगर',
    ],
  },
};

export default LOCALITIES_CONTENT;
