import ROLES from './roles.js';

export const PERMISSIONS = {
  // Property Management
  PROPERTY_READ: 'property:read',
  PROPERTY_CREATE: 'property:create',
  PROPERTY_VERIFY: 'property:verify',
  PROPERTY_UPDATE: 'property:update',
  PROPERTY_DELETE: 'property:delete',

  // Lead Management
  LEAD_READ: 'lead:read',
  LEAD_CREATE: 'lead:create',
  LEAD_ASSIGN: 'lead:assign',
  LEAD_UPDATE: 'lead:update',

  // Deals & Financials
  DEAL_READ: 'deal:read',
  DEAL_CLOSE: 'deal:close',
  COMMISSION_READ: 'commission:read',
  COMMISSION_PAYOUT: 'commission:payout',

  // Sub-Admin Delegation
  SUBADMIN_MANAGE: 'subadmin:manage',

  // Unmasked PII
  PII_UNMASKED: 'pii:unmasked'
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN_PARTNER]: [
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_CREATE,
    PERMISSIONS.PROPERTY_VERIFY,
    PERMISSIONS.PROPERTY_UPDATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.DEAL_READ,
    PERMISSIONS.DEAL_CLOSE,
    PERMISSIONS.COMMISSION_READ,
    PERMISSIONS.COMMISSION_PAYOUT
  ],
  [ROLES.FIELD_AGENT]: [
    PERMISSIONS.PROPERTY_CREATE,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.COMMISSION_READ
  ],
  [ROLES.VERIFICATION_STAFF]: [
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_VERIFY,
    PERMISSIONS.PROPERTY_UPDATE
  ],
  [ROLES.TELE_CALLER]: [
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_ASSIGN,
    PERMISSIONS.LEAD_UPDATE
  ],
  [ROLES.PROPERTY_OWNER]: [
    PERMISSIONS.PROPERTY_READ
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.PROPERTY_READ
  ]
};

export default {
  PERMISSIONS,
  ROLE_PERMISSIONS
};
