export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_PARTNER: 'ADMIN_PARTNER',
  FIELD_AGENT: 'FIELD_AGENT',
  VERIFICATION_STAFF: 'VERIFICATION_STAFF',
  TELE_CALLER: 'TELE_CALLER',
  PROPERTY_OWNER: 'PROPERTY_OWNER',
  CUSTOMER: 'CUSTOMER'
};

export const ROLE_LIST = Object.values(ROLES);

export default ROLES;
