export const PROPERTY_STATUS = {
  UNDER_VERIFICATION: 'UNDER_VERIFICATION',
  VACANT: 'VACANT',
  RENTED: 'RENTED',
  ON_SALE: 'ON_SALE',
  SOLD: 'SOLD',
  DEACTIVATED: 'DEACTIVATED'
};

export const RENT_STATUS = {
  PAID: 'PAID',
  PENDING: 'PENDING',
  DUE: 'DUE',
  OVERDUE: 'OVERDUE'
};

export const SITE_VISIT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW'
};

export const REQUEST_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

export default {
  PROPERTY_STATUS,
  RENT_STATUS,
  SITE_VISIT_STATUS,
  REQUEST_STATUS
};
